### ISSUE TITLE
Connection between Publisher & Subscriber lost when IP changes

### ISSUE THREAD

**Issue by aabm00** [Spacebrew/spacebrew#59]
Hello

I have my own Spacebrew server installed in Heroku and I have tried the button example and it works fine (changing the color background). The problem comes when my laptop's external IP, changes, For example from 10.179.151.165 to 10.231.195.45. Then I can see two version of the same button and the connection between publisher and subscriber is lost (In the same button) so when I press the button, the background color doesn't change.

There are something I have missed?

Thanks

**Comment by flysonic10** [comment]
Spacebrew uses both the publisher/subscriber name and its IP address to identify the endpoint. You might want to setup a static IP address on your laptop, or setup a script to bootstrap the connections using the admin API.

**Comment by aabm00** [comment]
Hello thanks for your answer.

I will be more explicit in the way I want to use the Spacebrew:

I will have different ArduinoYun boards connected via Wifi, behind a router in differents locations (they can be even different cities) sending sensors information to the Spacebrew server. They will be the Publishers. On the other hand there will be other clients that will receive and work with the data (Subscribers).
They will be connected through the Spacebrew Admin utility.

So, the information flow will be constant and can't lost the connection between Publishers and Subscribers when the Public IP of them changes.

Give an fixed IP is not an option because can be a lot of Yun boards sending information, so: 
Could you give more details about setup a script to bootstrap the connections using the admin API?

In this way the connection between Publishers and Subscribers would be maintained after the public IP has changed?

Thanks

**Comment by mangtronix** [comment]
I have the same problem for a similar use case, where my Spacebrew clients are behind a router whose IP address changes.

1. Heroku uses load balancers, so you're probably seeing the private IP address of the load balancers *inside Heroku*. Basically your Spacebrew client connects to the load balancer, then the load balancer connects to the Spacebrew server. Some more info here http://stackoverflow.com/questions/18264304/get-clients-real-ip-address-on-heroku  

2. https://groups.google.com/forum/#!topic/spacebrew-cc/g_096UBjEgo

3. I'm looking for a solution for this too! One way might be to run a server with a modified version of this script so that it matches the connections only using the name and ignores the address. https://github.com/Spacebrew/spacebrew/blob/master/spacebrew_live_persist.js#L165

There's also this "node_persistent_admin.js" that might already do that. https://github.com/Spacebrew/spacebrew/blob/master/node_persistent_admin.js

**Comment by quinkennedy** [comment]
The node_persistent_admin is designed for this sort of use case. You would
run that script after the Spacebrew server is already running, and then use
the CLI to set up the persistent routes you want. I believe it loads from a
file at start up, so you can configure it once, write the file, and not
have to configure it again.

**Comment by mangtronix** [comment]
Thanks! Yes, node_persistent_admin loads the persistent routes at startup. But first you have to manually save the routes (with "save") in the CLI. I added an example in my comment above.

**Comment by hgodinho** [comment]
Hello!
Im having some troubles in there.
My application is running on: http://spacebrew.github.io/spacebrew/admin/admin.html?server=gertrudes.herokuapp.com&port=80
When starts the application runs properly, but after a while the connections node get lost, it only get back when I refresh the admin page on browser.

When I try to run "node_persistent_admin.js" I get an error in CLI: 

> Error: connect ECONNREFUSED 127.0.0.1:9000
> at Object.exports._errnoException <util.js:1026:11>
> at exports._exceptionWithHostPort <util.js:1049:20>
> at TCPConnectWrap.afterConnect [as complete] <net.js:1085:14>
> code: 'ECONNREFUSED'.
> errno: 'ECONNREFUSED',
> syscall: 'connect',
> adreess: '127.0.0.1',
> port: 9000

What Im doing wrong?
