### ISSUE TITLE
Crash on 'toLowerCase' in handleConfigMessage

### ISSUE THREAD

**Issue by robotconscience** [Spacebrew/spacebrew#70]
Not sure if it's:
https://github.com/Spacebrew/spacebrew/blob/1b56f168dfcb5f1588cf76efc575124bd8d6e2f3/spacebrew.js#L718

or

https://github.com/Spacebrew/spacebrew/blob/1b56f168dfcb5f1588cf76efc575124bd8d6e2f3/spacebrew.js#L732

or both? But seems like this is one of the places the current server is crashing:

(log below from Amazon):
```
warn: [wss.onmessage] ERROR on line <undefined> while processing message
warn: TypeError: Cannot call method 'toLowerCase' of undefined
    at spacebrew.createServer.handleConfigMessage (/home/ec2-user/spacebrew/spacebrew.js:526:45)
    at WebSocket.spacebrew.createServer.wss.on.ws.on.connection.spacebrew_pong_validated (/home/ec2-user/spacebrew/spacebrew.js:155:41)
    at WebSocket.EventEmitter.emit (events.js:91:17)
    at Receiver.self._receiver.ontext (/home/ec2-user/spacebrew/node_modules/ws/lib/WebSocket.js:544:10)
    at Receiver.opcodes.1.finish (/home/ec2-user/spacebrew/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.opcodes.1.getData [as expectHandler] (/home/ec2-user/spacebrew/node_modules/ws/lib/Receiver.js:378:33)
    at Receiver.add (/home/ec2-user/spacebrew/node_modules/ws/lib/Receiver.js:93:24)
    at Socket.firstHandler (/home/ec2-user/spacebrew/node_modules/ws/lib/WebSocket.js:524:22)
    at Socket.EventEmitter.emit (events.js:88:17)
    at TCP.onread (net.js:395:14)
```

**Comment by quinkennedy** [comment]
fixed in #71
